### ISSUE TITLE
AbilityBuilder.define is not a function

### ISSUE THREAD

**Issue by haykokalipsis** [stalniy/casl-nuxt-example#2]
So im getting this error "_casl_ability__WEBPACK_IMPORTED_MODULE_0__.AbilityBuilder.define is not a function"

**Comment by KamranMaqbool** [comment]
getting same issue.
@stalniy any solutions ?

**Comment by stalniy** [comment]
It was removed in v4: https://github.com/stalniy/casl/blob/master/packages/casl-ability/CHANGELOG.md#breaking-changes

**Comment by stalniy** [comment]
See the docs https://casl.js.org/v4/en/
